Adding Library table filtering feature
SPAAM-community/AMDirT pull request #140
Opened 2023-12-15 15:38 UTC by maxibor

Adding the possibility to also filter on libraries.
Will require a documentation update for the tutorials.
Demonstration below.

Will close #119 

[amdirt_library_filtering_demo.webm](https://github.com/SPAAM-community/AMDirT/assets/8630837/1494d451-692e-4525-82de-2281da76d40e)

2023-12-18 11:06 UTC, maxibor commented
Convert tool is now fixed, as well as the issue described in #127

2023-12-18 12:59 UTC, maxibor commented
Also add download with sratoolkit to close #138

2024-01-15 05:28 UTC, jfy133 commented
Testing results:

- [ ] Library filtering
- [ ] Convert tool
- [ ]  SRAToolkit

2024-01-15 05:37 UTC, jfy133 reviewed
Nothing jumps out at me after looking at the code (based on my amateur knowledge).

Onto testing now.

2024-01-15 05:37 UTC, jfy133 commented on AMDirT/core/__init__.py
> +    # libraries = get_libraries(
Could be removed if not used anymore?

2024-01-15 05:37 UTC, jfy133 commented on AMDirT/viewer/streamlit.py
> +                                "You didn't select any library! Please select at least one library."
```suggestion
                                "You didn't select any libraries! Please select at least one library."
```

2024-01-15 06:01 UTC, jfy133 commented
@maxibor testing of viewer was fine, however I'm getting lots of errors with convert.

I try with both the samples and libraries files in the following zip

[Uploading amdirt-testing.zip…]()

And I get the following erros for both (but chaning the JSON schema it's validating against...)

```
$ AMDirT convert --sratoolkit samples.tsv ancientmetagenome-hostassociated
Traceback (most recent call last):
  File "/home/james/bin/miniconda3/envs/amdirt-dev/bin/AMDirT", line 33, in <module>
    sys.exit(load_entry_point('AMDirT', 'console_scripts', 'AMDirT')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/git/spaam-community/AMDirT/AMDirT/cli.py", line 179, in convert
    run_convert(**kwargs, **ctx.obj)
  File "/home/james/git/spaam-community/AMDirT/AMDirT/convert/__init__.py", line 71, in run_convert
    dataset_valid.append(v.validate_schema())
                         ^^^^^^^^^^^^^^^^^^^
  File "/home/james/git/spaam-community/AMDirT/AMDirT/validate/domain/__init__.py", line 235, in validate_schema
    for err in validator.iter_errors(self.dataset_json):
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/validators.py", line 354, in iter_errors
    for error in errors:
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/_legacy_validators.py", line 115, in items_draft6_draft7_draft201909
    yield from validator.descend(item, items, path=index)
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/validators.py", line 402, in descend
    for error in errors:
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/_validators.py", line 305, in properties
    yield from validator.descend(
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/validators.py", line 402, in descend
    for error in errors:
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/_validators.py", line 284, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/validators.py", line 432, in _validate_reference
    resolved = self._resolver.lookup(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/referencing/_core.py", line 586, in lookup
    retrieved = self._registry.get_or_retrieve(uri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/referencing/_core.py", line 336, in get_or_retrieve
    resource = registry._retrieve(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/jsonschema/validators.py", line 120, in _warn_for_remote_retrieve
    return referencing.Resource.from_contents(json.load(response))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/bin/miniconda3/envs/amdirt-dev/lib/python3.11/site-packages/referencing/_core.py", line 129, in from_contents
    raise exceptions.CannotDetermineSpecification(contents)
referencing.exceptions.CannotDetermineSpecification: {'enum': ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Arctic Ocean', 'Argentina', 'Armenia', 'Aruba', 'Ashmore and Cartier Islands', 'Atlantic Ocean', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Baltic Sea', 'Baker Island', 'Bangladesh', 'Barbados', 'Bassas da India', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Borneo', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Clipperton Island', 'Cocos Islands', 'Colombia', 'Comoros', 'Cook Islands', 'Coral Sea Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czech Republic', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europa Island', 'Falkland Islands (Islas Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern and Antarctic Lands', 'Gabon', 'Gambia', 'Gaza Strip', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Glorioso Islands', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and McDonald Islands', 'Honduras', 'Hong Kong', 'Howland Island', 'Hungary', 'Iceland', 'India', 'Indian Ocean', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Jan Mayen', 'Japan', 'Jarvis Island', 'Jersey', 'Johnston Atoll', 'Jordan', 'Juan de Nova Island', 'Kazakhstan', 'Kenya', 'Kerguelen Archipelago', 'Kingman Reef', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Line Islands', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mediterranean Sea', 'Mexico', 'Micronesia', 'Midway Islands', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Navassa Island', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'North Korea', 'North Macedonia', 'North Sea', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pacific Ocean', 'Pakistan', 'Palau', 'Palmyra Atoll', 'Panama', 'Papua New Guinea', 'Paracel Islands', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of the Congo', 'Reunion', 'Romania', 'Ross Sea', 'Russia', 'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'South Korea', 'South Sudan', 'Southern Ocean', 'Spain', 'Spratly Islan [...]

2024-01-15 06:03 UTC, jfy133 requested changes
Getting errors in `convert` :( see above

2024-01-15 10:34 UTC, jfy133 commented
[amdirt-error.zip](https://github.com/SPAAM-community/AMDirT/files/13937853/amdirt-error.zip)

2024-01-15 11:06 UTC, jfy133 commented
OK, I reinstalled everything from scratch (rather than `pip install -e .` within teh cloned branch in the directory, and now it's working. Convert looks to be working well.

Last question: usage just says `SAMPLES` . But description says 'samples and libraries', which is correct? Giving a library table doesn't work  for me - gives a schemas check error.

```
Usage: AMDirT convert [OPTIONS] SAMPLES TABLE_NAME

  Converts filtered samples and libraries tables to eager, ameta, taxprofiler, and fetchNGS input tables
  
  SAMPLES: path to filtered AncientMetagenomeDir samples tsv file
  TABLE_NAME: name of table to convert

```

2024-01-15 11:33 UTC, jfy133 commented
@maxibor :point_up:

2024-02-12 15:17 UTC, maxibor commented
@jfy133 Time to have another look ;)

2024-02-12 20:00 UTC, jfy133 approved these changes
`convert` working for me now!

In addition to the typo/left-over comment in my original review, I would suggest augmenting the main help description of `convert` to the following:


```
$ AMDirT convert --help
Usage: AMDirT convert [OPTIONS] SAMPLES TABLE_NAME

  Converts pre-filtered samples and libraries tables to eager, ameta, taxprofiler, and fetchNGS input tables.

Note: When supplying a pre-filtered libraries table to `--libraries`, the corresponding sample table is required!

  SAMPLES: path to filtered AncientMetagenomeDir samples tsv file
  TABLE_NAME: name of table to convert
  ```
  
  But otherwise LGTM after those three changes :)

2024-02-12 20:00 UTC, jfy133 commented on AMDirT/cli.py
> +    help=("(Optional) Path to libraries table"),
```suggestion
    help=("(Optional) Path to a pre-filtered libraries table"),
```

2024-02-12 20:00 UTC, jfy133 commented on AMDirT/convert/__init__.py
> +        libraries(str): Optional path to AncientMetagenomeDir filtered libraries tsv file
```suggestion
        libraries(str): Optional path to AncientMetagenomeDir pre-filtered libraries tsv file
```

2024-02-14 16:01 UTC, merged