Add the option to use aspera to download from ENA
SPAAM-community/AMDirT pull request #85
Opened 2022-11-09 14:03 UTC by alexhbnr

Adds the additional option "aspera" to the Streamlit sidebar and allows to download a Bash script that contains the commands to download the FastQ files from ENA using aspera instead of curl using the recommended commands following https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html#using-aspera

Since aspera requires the path to its installation location to load the config, this path is hidden using the Bash variable `ASPERA_PATH` that has to be set prior to executing the Bash script.

Would close #58.

2022-11-09 14:17 UTC, jfy133 requested changes
Missing soft-warning  that selecting aspera requires `aspera` to be installed, and ports _may_ need to be modified in the script depending on installation/firewall.

2022-11-09 14:52 UTC, alexhbnr commented
Where would you put the soft warnings? I would put them into the documentary on readthedocs, which I haven't added it to yet. Or do you think it's necessary to state into in the Streamlit app?

2022-11-10 07:35 UTC, jfy133 commented
> Where would you put the soft warnings? I would put them into the documentary on readthedocs, which I haven't added it to yet. Or do you think it's necessary to state into in the Streamlit app?

Good point, yes the docs will be sufficient I think.

2022-11-11 10:09 UTC, maxibor commented on AMDirT/filter/streamlit.py
>      st.session_state.dl_method = st.selectbox(
```suggestion
    st.session_state.dl_method = st.selectbox(
            label="", options=["curl", "nf-core/fetchngs", "aspera"]
    )
    if st.session_state.dl_method == "aspera":
        st.warning(
            "You will need to set the `${ASPERA_PATH}` environment variable. See [documentation](https://amdirt.readthedocs.io) for more information."
        )
```

2022-11-11 10:35 UTC, maxibor approved these changes

2022-11-11 10:36 UTC, maxibor commented
I suggest to include the aspera doc in a separate PR.
With the added warning about the aspera variable, this PR looks good to me.

2022-11-11 10:36 UTC, merged